### ISSUE TITLE
Error getting no Datat - tried everything

### ISSUE THREAD

**Issue by SebiWolze** [PhilippHee/CoinpaprikaAPI-ESP8266-Display#1]
Hey,
i tried everything but still get "Error getting no Data".
ESP is in my Wifi, pingable, I changed the Fingerprint of the API SSL Cert to 21e34dff083641691f1026ade59269f278fc1c01
Got the same Display like you, but still getting this error.
Even if I only try to display one Coin (BTC) the Error message still appears.

Do you have any idea what could be wrong still?
Thanks ahead.

**Comment by PhilippHee** [comment]
Hello,

thank you very much for your report! I have the same error. Since I had not turned on my ticker for a long time, I had not noticed it.

There were 2 errors:

1. The fingerprint has changed. The current one is (as you wrote): _21e34dff083641691f1026ade59269f278fc1c01_
If you don't want to always update the fingerprint, you could also use "_client.setInsecure();_" (see line 169).

2. I don't know why, but in the string of the retrieved data there are now a few characters at the beginning (before the character '_{_') that don't really belong there, so there were problems with the JSON parser. I have now added an appropriate query/statement to detect the correct beginning of the data stream (see line 213), so now everything should work again.

The errors are fixed in the current source code.

**Comment by SebiWolze** [comment]
Works for me, thank you very much, reall great project!
Trying to display some coins at the same time as 7D Change is not soo interesting for me. 
Great Job :-)
